SELECT 
    HE.EMP_NO AS EMP_NO, EMP_NAME, 
    CASE
        WHEN AVG(SCORE)>=96 THEN 'S'
        WHEN AVG(SCORE)>=90 THEN 'A'
        WHEN AVG(SCORE)>=80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE
        WHEN AVG(SCORE)>=96 THEN 0.2*SAL
        WHEN AVG(SCORE)>=90 THEN 0.15*SAL
        WHEN AVG(SCORE)>=80 THEN 0.1*SAL
        ELSE 0
    END BONUS
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO