SELECT MONTH(START_DATE) AS MONTH, C.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH(C.START_DATE), C.CAR_ID
ORDER BY 1, 2 DESC