SELECT A.ID AS ID, B.FISH_NAME AS FISH_NAME, LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE A.FISH_TYPE = FISH_INFO.FISH_TYPE)
ORDER BY ID