SELECT F1.CATEGORY, F1.PRICE MAX_PRICE, F1.PRODUCT_NAME
FROM FOOD_PRODUCT F1
WHERE CATEGORY IN ('과자','국','김치','식용유')
    AND F1.PRICE = (
        SELECT MAX(F2.PRICE)
        FROM FOOD_PRODUCT F2
        WHERE F2.CATEGORY = F1.CATEGORY
    )
GROUP BY CATEGORY	
ORDER BY MAX_PRICE DESC